/*
This express middleware function attempts to decode a JSON Web Token that is
generated by the Sabio .NET API server.

* If the token is decoded successfully, req.user will contain information about the user.
* If the token is bad/not present, req.user will be set to null. 
*/
const { userFromJWT } = require("../jwt");

module.exports = {
  userFromJWTFilter
};

function userFromJWTFilter(req, res, next) {
  try {
    const authCookie = req.cookies.authentication;
    if (authCookie) {
      req.user = userFromJWT(authCookie);
    }
  } catch (e) {
    req.user = null;
  }
  next();
}
